/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Ferramenta;
import Model.Amigo;
import Model.Emprestimo;
import java.awt.Toolkit;


public class TelaInicial extends javax.swing.JFrame {

         private Ferramenta ferramentaobj; 
         private Amigo amigoobj;
         private Emprestimo emprestimoobj;
         
    public TelaInicial() {
        initComponents();
        this.ferramentaobj = new Ferramenta();
        this.amigoobj = new Amigo();
        this.emprestimoobj = new Emprestimo();
        setIcon();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cad_Amigos = new javax.swing.JMenuItem();
        ger_Amigos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cad_Ferramentas = new javax.swing.JMenuItem();
        ger_Ferramentas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rea_Emprestimo = new javax.swing.JMenuItem();
        ger_Emprestimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 89));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel2.setText("SISTEMA DE EMPRÉSTIMOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 181, 6, 186);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo clean code2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 181, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanel2);
        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Amigos");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cad_Amigos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cad_Amigos.setText("Cadastrar Amigos");
        cad_Amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_AmigosActionPerformed(evt);
            }
        });
        jMenu1.add(cad_Amigos);

        ger_Amigos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ger_Amigos.setText("Gerenciar Amigos");
        ger_Amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ger_AmigosActionPerformed(evt);
            }
        });
        jMenu1.add(ger_Amigos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ferramentas");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cad_Ferramentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cad_Ferramentas.setText("Cadastrar Ferramentas");
        cad_Ferramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_FerramentasActionPerformed(evt);
            }
        });
        jMenu2.add(cad_Ferramentas);

        ger_Ferramentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ger_Ferramentas.setText("Gerenciar Ferramentas");
        ger_Ferramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ger_FerramentasActionPerformed(evt);
            }
        });
        jMenu2.add(ger_Ferramentas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empréstimos");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        rea_Emprestimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rea_Emprestimo.setText("Realizar empréstimos");
        rea_Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rea_EmprestimoActionPerformed(evt);
            }
        });
        jMenu3.add(rea_Emprestimo);

        ger_Emprestimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ger_Emprestimo.setText("Gerenciar empréstimos");
        ger_Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ger_EmprestimoActionPerformed(evt);
            }
        });
        jMenu3.add(ger_Emprestimo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cad_AmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_AmigosActionPerformed
        CadastrarAmigo objetotela1 = new CadastrarAmigo();
        objetotela1.setVisible(true);
    }//GEN-LAST:event_cad_AmigosActionPerformed

    private void ger_AmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ger_AmigosActionPerformed
        GerenciaAmigo objetotela2 = new GerenciaAmigo();
        objetotela2.setVisible(true);
    }//GEN-LAST:event_ger_AmigosActionPerformed

    private void cad_FerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_FerramentasActionPerformed
        CadastrarFerramenta objetotela3 = new CadastrarFerramenta();
        objetotela3.setVisible(true);
    }//GEN-LAST:event_cad_FerramentasActionPerformed

    private void ger_FerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ger_FerramentasActionPerformed
        GerenciaFerramenta objetotela4 = new GerenciaFerramenta();
        objetotela4.setVisible(true);
    }//GEN-LAST:event_ger_FerramentasActionPerformed

    private void rea_EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rea_EmprestimoActionPerformed
        RealizarEmprestimo objetotela5 = new RealizarEmprestimo();
        objetotela5.setVisible(true);
    }//GEN-LAST:event_rea_EmprestimoActionPerformed

    private void ger_EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ger_EmprestimoActionPerformed
        GerenciaEmprestimo objetotela6 = new GerenciaEmprestimo();
       objetotela6.setVisible(true);
    }//GEN-LAST:event_ger_EmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cad_Amigos;
    private javax.swing.JMenuItem cad_Ferramentas;
    private javax.swing.JMenuItem ger_Amigos;
    private javax.swing.JMenuItem ger_Emprestimo;
    private javax.swing.JMenuItem ger_Ferramentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem rea_Emprestimo;
    // End of variables declaration//GEN-END:variables

    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo clean code1.png")));
    }
}
